name: Deploy Components to Mainnet
on:
  push:
    branches: [main]
jobs:
  deploy-mainnet:
    uses: NEARBuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      bw-legacy: false
      deploy-env: "mainnet"
      app-name: "embeds.near"
      deploy-account-address: "embeds.near"
      signer-account-address: "embeds.near"
      signer-public-key: ${{ vars.SIGNER_PUBLIC_KEY }}
    secrets: 
      SIGNER_PRIVATE_KEY: ${{ secrets.SIGNER_PRIVATE_KEY }}
