name: Deploy Components to Testnet
on:
  push:
    branches: [develop]
jobs:
  deploy-mainnet:
    uses: NEARBuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      bw-legacy: false
      build-env: "testnet"
      deploy-env: "testnet"
      app-name: "embeds.near"
      deploy-account-address: "embeds.testnet"
      signer-account-address: "embeds.testnet"
      signer-public-key: ${{ vars.TESTNET_SIGNER_PUBLIC_KEY }}
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.TESTNET_SIGNER_PRIVATE_KEY }} // then configure this in your Github/Settings/Actions
